### ISSUE TITLE
Update nested tick lists

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-brochure-theme-design#10]
**Update: I think conclusion is that any lists nested under a nested tick lists won't have the tick, as per [example](https://github.com/ubuntudesign/vanilla-brochure-theme-design/issues/10#issuecomment-276667451).**

---

See top of https://www.ubuntu.com/download/cloud

@spencerbygraves @kwm14 @joanasa89 Thoughts?

**Comment by kwm14** [comment]
@yaili In MAAS we use something similar but believe it's a called 'list tree' (I could be wrong)?

Maybe we could adopt this styling with some elements removed?

I quickly mocked together a visual below for reference.

**Current in MAAS - Services** 
![screen shot 2017-02-01 at 13 58 10](https://cloud.githubusercontent.com/assets/17748020/22509654/e73f5c7a-e886-11e6-8231-3c5024f70455.png)

**Updated for Ubuntu - Cloud**
![nested-list-example](https://cloud.githubusercontent.com/assets/17748020/22510087/85693eb0-e888-11e6-9e9f-f52944a3650f.png)

**Comment by joanasa89** [comment]
Would be possible to mix tick list & Unordered list ?  Something like this maybe?
![list](https://cloud.githubusercontent.com/assets/21334617/22510155/c168f1e4-e888-11e6-827c-aaac5cabfc3c.jpg)

**Comment by yaili** [comment]
Interesting, both. I think the tree pattern looks good, but it's usually applied to file views, right @anthonydillon @barrymcgee ?

Joana's example is less jarring than the current implementation on https://www.ubuntu.com/download/cloud

**Comment by spencerbygraves** [comment]
All in green ticks looks ok in MAAS, but all orange looks too much.

One tick at the top level and the rest bulleted seems better to me.

**Comment by yaili** [comment]
@anthonydillon @barrymcgee ?

**Comment by barrymcgee** [comment]
I prefer @joanasa89's example - having all tick icons gives the impression they have all semantic equal weight which they do not.

**Comment by anthonydillon** [comment]
I'm +1 on @joanasa89 example too. I think all ticks looks nicer but harder to see the hierarchy.

**Comment by anthonydillon** [comment]
This is currently available with the latest Vanilla:
https://codepen.io/anthonydillon/pen/MpGWYe

**Comment by barrymcgee** [comment]
It's not the exact same - Joana's example has round bullets followed by round outlines. Your example has round outlines followed by square bullets?

**Comment by anthonydillon** [comment]
Sure but i feel the example is more correct as that is the nested list base
style.

**Comment by yaili** [comment]
We should follow the same styles as normal nested lists, is that what you've done @anthonydillon ?

**Comment by anthonydillon** [comment]
Yes the nested list styles are browser default.
