### ISSUE TITLE
Should headings with external icon be all caps or sentence case?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-brochure-theme-design#11]
We haven't used this pattern consistently:
- Second row in homepage uses all caps: https://www.ubuntu.com/
- BitTorrent section is sentence case: https://www.ubuntu.com/download/alternative-downloads
- Latest news in dev.u.c is all caps: https://developer.ubuntu.com/core
- Second row in /juju is sentence case: https://www.ubuntu.com/cloud/juju

I prefer all caps but would like get your input, @spencerbygraves @kwm14 @joanasa89

**Comment by kwm14** [comment]
+1 for all caps on headings

**Comment by joanasa89** [comment]
+1 -  all caps ; font size: 16px

**Comment by spencerbygraves** [comment]
Happy to stay with all caps.

**Comment by yaili** [comment]
Great, thank you!
