### ISSUE TITLE
Proposal - Footer

### ISSUE THREAD

**Issue by joanasa89** [ubuntudesign/vanilla-brochure-theme-design#13]
To be consistent with ubuntu.com, I would like to purpose a new design for footer.
**Large screen**
1. Sections from the top navigation
2. Other links
3. Social media icons - On the bottom-right , aligned with 'other links'
4. Legal information

**Medium & Small screens**
1. Back to the top button 
2. Accordion menus - with the sections from the top navigation
3. Global Navigation - Global nav below the main sections 
4. Other links
5. Legal information
6. Social media icons - the order should be: twitter, facebook, linkedin, google +

Fontsize : 13px
Colours : #111 ; #666 and #cdcdcd (for divider)

Let me know your thoughts 

**Screenshots**
![footer-desktop-final](https://cloud.githubusercontent.com/assets/21334617/24619468/fa8976a4-1891-11e7-8908-fe2a3601a410.jpg)
![footer-mobile-final](https://cloud.githubusercontent.com/assets/21334617/24619467/fa896dda-1891-11e7-9962-c5279b46e3f7.jpg)
![footer-mobile-final-open](https://cloud.githubusercontent.com/assets/21334617/24619466/fa895e76-1891-11e7-8c5e-09bec5a7a6dc.jpg)

**Comment by yaili** [comment]
Notes from the working group:
- For the footer to be a Vanilla, or Brochure theme, pattern, it needs to be simplified a little bit more to be more generic

Will mark this as not accepted and we can revisit later if/when needed.
