### ISSUE TITLE
Add states to strips pattern

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-brochure-theme-design#15]
Could you please add `is-deep` and `is-bordered` to the strip pattern spec please.

**Comment by yaili** [comment]
@barrymcgee I assume the last variable [here](https://github.com/vanilla-framework/vanilla-framework/issues/728#issuecomment-287099192) is xx-large, not x-large, correct?

**Comment by anthonydillon** [comment]
In fact there's `$sp-xxx-large`. https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_settings_spacing.scss

**Comment by yaili** [comment]
OK, this is done now: https://github.com/ubuntudesign/vanilla-brochure-theme-design/tree/master/Strip
