### ISSUE TITLE
Adapt Vanilla notifications for cookie message pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-brochure-theme-design#9]
Vanilla notifications: https://github.com/CanonicalLtd/juju-design/issues/151#issuecomment-246964507

Does notification have to be in a certain position on the page? A certain size? Can is disappear after first page visited?

**Comment by anthonydillon** [comment]
> Does notification have to be in a certain position on the page?

No, it can be absolutely positioned.

> A certain size

It would be nice to keep the sizing uniform as to not introduce a new variant.

> Can is disappear after first page visited?

Yes, and should do.

**Comment by barrymcgee** [comment]
@yaili Has your question been answered here? If so, can you close and if not, can you specific the action that needs to be taken?

**Comment by yaili** [comment]
@barrymcgee yes, I've updated the issue to be a card for me to work on.

**Comment by yaili** [comment]
I've had a look at using the notification pattern for the cookie message, positioned in the same way we do now (sticky footer).

I've tried in all 4 notification styles:
- neutral
- positive
- negative
- warning

And with the option of either constraining the text to the max-width of the site or being full width. Also, the copy of the "Dismiss" could be improved.

I think the neutral style makes more sense for the content of the cookie message, but I'd like to hear other people's thoughts.

@pmahnke @kwm14 @spencerbygraves , comments?

![cookie full width neutral](https://cloud.githubusercontent.com/assets/223966/23553692/d1ca1f7e-0019-11e7-8c54-306abab574e1.png)

![cookie full width positive](https://cloud.githubusercontent.com/assets/223966/23553702/d6eb6972-0019-11e7-8c65-8991f2b269bf.png)

![cookie full width negative](https://cloud.githubusercontent.com/assets/223966/23553715/e1a8951a-0019-11e7-8a31-a5970f517ef2.png)

![cookie full width warning](https://cloud.githubusercontent.com/assets/223966/23553721/eaec15d4-0019-11e7-8a88-27f8d94b4f12.png)

![cookie max width neutral](https://cloud.githubusercontent.com/assets/223966/23553727/ef80c694-0019-11e7-8c7e-52d5781aef8e.png)

**Comment by spencerbygraves** [comment]
I agree that the grey neutral style makes sense, as it doesn't really fit into the other categories.

It's quite a long line width to read. Perhaps we could make the box/card the width of the grid and centred?

**Comment by kwm14** [comment]
+1 on neutral style, looks really good.

Agree with @spencerbygraves it is quite long in the first few versions, I like the layout you've used in v5 using our current grid.

**Comment by yaili** [comment]
@kwm14 cool, thanks. @spencerbygraves do you think the last option makes it easier to read, or do you mean making the whole box narrower?

**Comment by spencerbygraves** [comment]
Yeah, I was thinking make the box narrower, like this:

![image](https://cloud.githubusercontent.com/assets/9105999/23558090/3e496956-002a-11e7-8205-4c88871d14ea.png)

**Comment by yaili** [comment]
Ah, nice. I think that looks good. @marcush do you have any thoughts?

**Comment by anthonydillon** [comment]
Could we move the dismiss link to the right? Just to give the notification
a quick actionable area and to allow room from the link in the copy.

**Comment by spencerbygraves** [comment]
That would be a new version. At the moment we have the link on the right on the grouped version.

https://github.com/CanonicalLtd/juju-design/issues/151

**Comment by yaili** [comment]
@spencerbygraves if we created a variation for the cookie with the dismiss to the right, like in the grouped version, do you think it would look better if the dismiss aligned at the top right of the box?

**Comment by spencerbygraves** [comment]
Happy to try it.

We use text in the notifications as the word is at the end of the sentence, and explains that there is more than one notification in the grouped version. But perhaps here it should be the close icon?

![image](https://cloud.githubusercontent.com/assets/9105999/23611472/751275ee-026f-11e7-881b-ab8c7c2787c5.png)

**Comment by yaili** [comment]
I like that. Will tag this thread as a proposal.

**Comment by barrymcgee** [comment]
Can this issue now be closed? Seems like it's been superseded by https://github.com/vanilla-framework/vanilla-brochure-theme/issues/48 ?

**Comment by yaili** [comment]
Yes, but I'm not sure who should be assigned the other issue. @pmahnke ?

**Comment by anthonydillon** [comment]
This has been done. The cookie policy now lives [in its own repo](https://github.com/canonical-webteam/cookie-policy).
